### PR TITLE
Add unit tests for LibraryContainer class methods

### PR DESCRIPTION
**Pull request by ellensi**
*[DYN-638](https://jira.autodesk.com/browse/DYN-638) Add unit tests for LibraryContainer class methods*

### Purpose

Adding a jest test file named `LibraryContainerTests.tsx` for testing `setLoadedTypesJson()` and `setLayoutSpecsJson()` class methods in `LibraryContainer.tsx`.

For better categorization, the file `jesttest.tsx` is renamed to `UITests.tsx`.

```
__tests__/UITests.tsx
  sample test
    √ should add two numbers

  LibraryContainer UI
    √ should recognize mouse click event and change event state

__tests__/LibraryContainerTests.tsx
  LibraryContainer class
    √ should throw exception if set with an invalid loadedTypesJson
    √ should throw exception if set with an invalid layoutSpecsJson
    √ should set the loadedTypesJson correctly
    √ should set the layoutSpecsJson correctly
    √ should populate and render the LibraryItems correctly
```

### Reviewers

@monikaprabhu @gohb

### CODE REVIEW

**Comment by Benglin** [comment]
Thanks for these tests, they are looking great, thanks! 👍

**Comment by ellensi** [comment]
Hi @monikaprabhu could you take a brief look on this new structuring of the jest cases? Thanks!

**Comment by monikaprabhu** [comment]
@ellensi LGTM. fyi... @fanwgwg

**Comment by ellensi** [comment]
Thanks peeps, let's get things done sooner.

**Pull request merged**
