### PR TITLE
Security Update

### PR DESCRIPTION
**Pull request by QilongTang**
Security update required for component minimist-0.0.8. It appears that minimist needs to be updated to 1.2.2 at the minimum to resolve this.

After updating webpack to be latest, I found my local minimist package become up to date:
```
  "name": "minimist",
  "version": "1.2.6",
```
FYI: @aparajit-pratap @mjkkirschner Please remind me if after merging this, I need to make a PR in Dynamo

### CODE REVIEW

**Review by zeusongit — APPROVED** [review]

**Comment by mjkkirschner** [comment]
@QilongTang I find it a bit hard to believe that updating to webpack 5 went so easily... did this actually build and run?

**Comment by mjkkirschner** [comment]
see my PR trying to update to 5 here.

**Comment by QilongTang** [comment]
> - I successfully accomplished it, but it broke the i



> @QilongTang I find it a bit hard to believe that updating to webpack 5 went so easily... did this actually build and run?

I built locally and was able to run the library, I can test in Dynamo Monday

**Comment by QilongTang** [comment]
@mjkkirschner I checked your earlier PR, seems like most of the changes are there already. What I had to do is update CSS loader and Webpack CLI, also need to get rid of file loder. I tested locally and it looks fine in Chrome and Dynamo

**Comment by QilongTang** [comment]
@mjkkirschner I take my words back, for some reason.. The testing results are different today, although everything looks good on Chrome, icons dont load for me on Dynamo side:

Dynamo side:
image

Chrome side:
image

**Comment by mjkkirschner** [comment]
@QilongTang yes, thats because chrome loads the data from a server, but the in dynamo context there is no server, the images are sent as base64 encoded strings - take a look at this PR:
https://github.com/DynamoDS/Dynamo/pull/12727

**Pull request merged**
