### PR TITLE
Change font format from OTF to WOFF

### PR DESCRIPTION
**Pull request by ellensi**
Because WOFF is designed for web and somehow looks better (probably due to proper hinting).

### CODE REVIEW

**Comment by Racel** [comment]
FYI @QilongTang...are we using WOFF on playground?

**Comment by QilongTang** [comment]
@Racel We are using tff

**Comment by Benglin** [comment]
Hi @ellensi, if you can give a more elaborated screen comparison that would make this selection easier. @Racel @QilongTang, can we have a sneak peak into the playground? @ramramps mentioned this to me a while back and I have been curious ever since (pardon me if it is broadcasted on Slack, I am not too up-to-date there).

**Comment by ellensi** [comment]
OTF on the left, WOFF on the right. Note that the **bold** types (blue highlights) are noticeably uneven in OTF, but other differences in non-bold texts are cosmetics only.

image

image

image

image

Note: These screenshots are taken using Chrome on Windows.

**Comment by Benglin** [comment]
Since we are staying with Artifakt font, just a format change (and also the look/feel is visibly better), I'm merging this in for now. Thanks folks!

**Comment by Racel** [comment]
@Benglin - Sending you a link on slack about the playground...

**Pull request merged**
